# Generated by Django 5.2.2 on 2025-06-10 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_brand_categoryanim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "Price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.CreateModel(
            name="CatalogProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProductName",
                    models.CharField(max_length=100, verbose_name="Название продукта"),
                ),
                (
                    "PriceOfProduct",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена продукта"
                    ),
                ),
                (
                    "DescriptionProduct",
                    models.CharField(max_length=300, verbose_name="Описание продукта"),
                ),
                (
                    "Img",
                    models.ImageField(
                        upload_to="products/%Y/%m/%d",
                        verbose_name="Изображение продукта",
                    ),
                ),
                ("Quantity", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "Brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.brand",
                        verbose_name="Бренд",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт каталога",
                "verbose_name_plural": "Продукты каталога",
            },
        ),
        migrations.CreateModel(
            name="CategoryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "CategoryName",
                    models.CharField(
                        max_length=25, verbose_name="Название категории товара"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория товара",
                "verbose_name_plural": "Категории товаров",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AddedAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные",
            },
        ),
        migrations.CreateModel(
            name="Orderr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TotalAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Общая сумма"
                    ),
                ),
                (
                    "OrderDate",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
                (
                    "CardNumber",
                    models.CharField(max_length=20, verbose_name="Номер карты"),
                ),
                (
                    "ExpiryDate",
                    models.CharField(max_length=5, verbose_name="Срок действия карты"),
                ),
                ("CVC", models.CharField(max_length=3, verbose_name="CVC код")),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="PetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TypeName",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="Тип животного"
                    ),
                ),
                (
                    "Description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип животного",
                "verbose_name_plural": "Типы животных",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "PromotionName",
                    models.CharField(max_length=100, verbose_name="Название акции"),
                ),
                (
                    "DiscountPercentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Процент скидки"
                    ),
                ),
                ("StartDate", models.DateTimeField(verbose_name="Дата начала")),
                ("EndDate", models.DateTimeField(verbose_name="Дата окончания")),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rating", models.PositiveIntegerField(verbose_name="Рейтинг")),
                (
                    "ReviewText",
                    models.TextField(max_length=1000, verbose_name="Текст отзыва"),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.DeleteModel(
            name="CategoryAnim",
        ),
        migrations.AddField(
            model_name="cart",
            name="CatalogProduct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.catalogproduct",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="catalogproduct",
            name="Category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.categoryproduct",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="CatalogProduct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.catalogproduct",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="categoryproduct",
            name="PetType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.pettype",
                verbose_name="Тип животного",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="CatalogProduct",
            field=models.ManyToManyField(
                blank=True, to="shop.catalogproduct", verbose_name="Продукты"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="CatalogProduct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.catalogproduct",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("User", "CatalogProduct")},
        ),
    ]
